In [ ]:
import pandas as pd
renewable_sources = ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],
    "Cost (Million $)": [200, 400, 350, 100, 250],
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022,2025,2023]
}
projects_df = pd.DataFrame(data)

projects_df


Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
projects_df[2:4]

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
2  Hydropower Y  Hydropower            200               350  Washington   
3  Solar Roof Z       Solar             50               100      Nevada   

   Completion Year  
2             2022  
3             2025

In [ ]:
projects_df.dtypes

Project             object
Technology          object
Capacity (MW)        int64
Cost (Million $)     int64
Location            object
Completion Year      int64
dtype: object

In [ ]:
projects_df.shape

(5, 6)

In [ ]:
projects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes


In [ ]:
projects_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [9]:
import pandas as pd
renewable_sources = ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],
    "Cost (Million $)": [200, 400, 350, 100, 250],
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022,2025,2023]
}
projects_df = pd.DataFrame(data)

projects_df
# Filter projects with capacity greater than 100 MW
high_capacity_projects = projects_df[projects_df["Capacity (MW)"] > 100]

print("\nProjects with Capacity Greater than 100 MW:")
print(high_capacity_projects)


Projects with Capacity Greater than 100 MW:
          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [10]:
projects_df["cost per MW"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]
print("\nDataFrame with Cost per MW :")
projects_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [11]:
projects_df.isnull().sum()

Project             0
Technology          0
Capacity (MW)       0
Cost (Million $)    0
Location            0
Completion Year     0
dtype: int64

In [15]:
# Aggregate the total capacity and cost
total_capacity = projects_df["Capacity (MW)"].sum()
total_cost = projects_df["Cost (Million $)"].sum()
print(f"Total Capacity of all projects: {total_capacity} MW")
print(f"Total Cost of all projects: ${total_cost} million")

Total Capacity of all projects: 800 MW
Total Cost of all projects: $1300 million


In [16]:
# Group by "Technology" and calculate total capacity for each type
grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("\nTotal Capacity by Technology:")
print(grouped_data)


Total Capacity by Technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [22]:
import numpy as np

ec=[1200,3400,2900,1800,2500]
energy_consumption=np.array(ec)
print("Energy consumption (in Mwh) for different renewable sources:")
print(energy_consumption)

Energy consumption (in Mwh) for different renewable sources:
[1200 3400 2900 1800 2500]


In [24]:
A =np.ones(4)
A2 = np.ones((2,2))
print(A)
print("\n",A2)

[1. 1. 1. 1.]

 [[1. 1.]
 [1. 1.]]


In [25]:
M =np.zeros(4)
print(M)

[0. 0. 0. 0.]


In [26]:
total_consumption = np.sum(energy_consumption)
print(f"Total Energy Consumption: {total_consumption} MWh")

Total Energy Consumption: 11800 MWh


In [28]:
import numpy as np

ec=[1200,3400,2900,1800,2500]
energy_consumption=np.array(ec)

mean_consumption = np.mean(energy_consumption)
print(f"Mean Energy Consumption: {mean_consumption} MWh")

Mean Energy Consumption: 2360.0 MWh


In [32]:
energy_consumption2 =np.array([1200, 3400, 2900, 1800, 2500,1800])
reshaped_array =energy_consumption2.reshape(3,2)
print("Reshaped Array consumption Array (3x2):")
print(reshaped_array)

Reshaped Array consumption Array (3x2):
[[1200 3400]
 [2900 1800]
 [2500 1800]]


In [33]:
reshaped_array.flatten()

array([1200, 3400, 2900, 1800, 2500, 1800])

In [34]:
reshaped_array.T

array([[1200, 2900, 2500],
       [3400, 1800, 1800]])

In [37]:
import numpy as np

ec=[1200,3400,2900,1800,2500]
energy_consumption=np.array(ec)

resize_array = np.resize(energy_consumption, (3, 3))
print(resize_array)